### ISSUE TITLE
Huge amounts of buffering

### ISSUE THREAD

**Issue by sonefiler** [ChoosenEye/Twitch-Adblock-Bugs#3]
Running this adblock extension makes every twitch stream incredibly laggy. Like, it will buffer every ten seconds or so for about five seconds. I'm using Chrome version 88.0.4324.146 with no other adblock extensions running at the same time, on Windows 10.

**Comment by ChoosenEye** [comment]
The Extension is replacing the Twitch Stream Playlist, currently there is only one server doing these replacements, located in the EU, so if you are far away from the server listed in the playlist you maybe have problems loading the files for the stream, this results in laggy experience.

Because the Servers for replacing, would adding more cost this project i currently can't provide servers in the US or in other Regions.

**Comment by sonefiler** [comment]
How much would a US server cost per month?

**Comment by ChoosenEye** [comment]
technically i would like to split west/east coast, so there would be 2 additional Servers for resolving and 1 load balancer for routing the requests to the correct endresolving locations.

all over all this would be around 20-30$ per month.

**Comment by swiftaes** [comment]
I can let you use part of my dedicated server located in central us also would there be a way we could self host it on our own servers?

**Comment by ChoosenEye** [comment]
thank you for your offer, i currently don't want to share the Server Side Code in Public, Twitch is currently not blocking this method and mostly i think because they don't know what exactly the Server does. 

If you wanna support the Extension so i can do Geo Redundancy Server Hosting a PayPal Button is included in the Extension.
